version: "3.9"

services:
  mongodb:
    restart: always
    image: mongo:5.0
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - "./database:/data/db"
    command: mongod --quiet --logpath /dev/null --port ${MONGODB_PORT}

    networks:
      - db

  api:
    build:
      dockerfile: services/api/Dockerfile.dev
      context: .
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongodb
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - frontend
      - db

  front:
    build:
      dockerfile: services/front/Dockerfile
      context: .
      target: deps
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - api
    command: yarn dev
    env_file:
      - .env
    networks:
      - frontend

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - "./cache:/data"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - db

networks:
  frontend:
  db:
