version: "3.9"

services:
  mongodb:
    restart: always
    image: mongo:5.0
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - "./database:/data/db"
    command: --quiet

    networks:
      - db

  api:
    build:
      dockerfile: services/api/Dockerfile.dev
      context: .
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongodb
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - frontend
      - db

  # next:
  #   restart: always
  #   depends_on:
  #     - api
  #   build:
  #     context: ./frontEnd
  #   volumes:
  #     - ./frontEnd:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - frontend

  # nginx:
  #   restart: always
  #   build:
  #       context: ./nginx
  #   ports:
  #       - "80:80"
  #       - "443:443"

networks:
  frontend:
  db:
