version: '3.9'
services:

  mongodb:
    restart: always
    image: mongo:5.0
    ports:
      - "27017:27017" 
    volumes:
      - './database:/data/db'
    networks:
      - db


  api:
    build: 
      dockerfile: services/api/Dockerfile.dev
      context: .
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "8080:8000"
    depends_on:
      - mongodb
    command: yarn start:dev
    networks:
      - api
      - db



  
  # nginx:
  #   restart: always
  #   build:
  #       context: ./nginx
  #   ports:
  #       - "80:80"
  #       - "443:443"

  # react:
  #   build:
  #       context: ./app
  #   ports:
  #       - "3000:3000"
  #   networks:
  #     - frontend



networks:
  api:
  db: